# This rule rewrites requests from admin.yourproject.tech
# to the /admin path of your site.
[[redirects]]
  from = "https://admin.yourproject.tech/*"
  to = "/admin/:splat"
  status = 200 # This makes it a rewrite, not a redirect
  force = true